repos:
  - repo: local
    hooks:
      - id: ruff-check-backend
        name: ruff check (backend)
        entry: ruff check --config backend/pyproject.toml --force-exclude --fix
        language: system
        types: [python]
        files: ^backend/

      - id: ruff-format-backend
        name: ruff format (backend)
        entry: ruff format --config backend/pyproject.toml --force-exclude
        language: system
        types: [python]
        files: ^backend/