name: FastAPI Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        
      - name: Set up Docker Buildx
        uses: actions/setup-buildx-action@v4

      - name: Start Containers
        run: docker compose up -d --build

      - name: Run Tests in Container
        run: docker compose exec -T backend pytest

      - name: Stop Containers
        if: always()
        run: docker compose down -v