MIN_USERNAME_LENGTH = 3
MAX_USERNAME_LENGTH = 50
MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 50

# Habit Schema Constants
MIN_HABIT_NAME_LENGTH = 1
MAX_HABIT_NAME_LENGTH = 100

MAX_HABIT_DESCRIPTION_LENGTH = 255
